//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DumpFilters) DeepCopyInto(out *DumpFilters) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DumpFilters.
func (in *DumpFilters) DeepCopy() *DumpFilters {
	if in == nil {
		return nil
	}
	out := new(DumpFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusDumpLoader) DeepCopyInto(out *PrometheusDumpLoader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusDumpLoader.
func (in *PrometheusDumpLoader) DeepCopy() *PrometheusDumpLoader {
	if in == nil {
		return nil
	}
	out := new(PrometheusDumpLoader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusDumpLoader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusDumpLoaderList) DeepCopyInto(out *PrometheusDumpLoaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrometheusDumpLoader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusDumpLoaderList.
func (in *PrometheusDumpLoaderList) DeepCopy() *PrometheusDumpLoaderList {
	if in == nil {
		return nil
	}
	out := new(PrometheusDumpLoaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusDumpLoaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusDumpLoaderSpec) DeepCopyInto(out *PrometheusDumpLoaderSpec) {
	*out = *in
	if in.TimeRange != nil {
		in, out := &in.TimeRange, &out.TimeRange
		*out = new(TimeRange)
		(*in).DeepCopyInto(*out)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(DumpFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.SarConversion != nil {
		in, out := &in.SarConversion, &out.SarConversion
		*out = new(SarConversionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusDumpLoaderSpec.
func (in *PrometheusDumpLoaderSpec) DeepCopy() *PrometheusDumpLoaderSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusDumpLoaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusDumpLoaderStatus) DeepCopyInto(out *PrometheusDumpLoaderStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SarConversionStatus != nil {
		in, out := &in.SarConversionStatus, &out.SarConversionStatus
		*out = new(SarConversionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusDumpLoaderStatus.
func (in *PrometheusDumpLoaderStatus) DeepCopy() *PrometheusDumpLoaderStatus {
	if in == nil {
		return nil
	}
	out := new(PrometheusDumpLoaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SarConversionSpec) DeepCopyInto(out *SarConversionSpec) {
	*out = *in
	if in.CustomMetrics != nil {
		in, out := &in.CustomMetrics, &out.CustomMetrics
		*out = make([]MetricMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SarConversionSpec.
func (in *SarConversionSpec) DeepCopy() *SarConversionSpec {
	if in == nil {
		return nil
	}
	out := new(SarConversionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SarConversionStatus) DeepCopyInto(out *SarConversionStatus) {
	*out = *in
	if in.TimeRangeCovered != nil {
		in, out := &in.TimeRangeCovered, &out.TimeRangeCovered
		*out = new(TimeRange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SarConversionStatus.
func (in *SarConversionStatus) DeepCopy() *SarConversionStatus {
	if in == nil {
		return nil
	}
	out := new(SarConversionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricMapping) DeepCopyInto(out *MetricMapping) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricMapping.
func (in *MetricMapping) DeepCopy() *MetricMapping {
	if in == nil {
		return nil
	}
	out := new(MetricMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeRange) DeepCopyInto(out *TimeRange) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeRange.
func (in *TimeRange) DeepCopy() *TimeRange {
	if in == nil {
		return nil
	}
	out := new(TimeRange)
	in.DeepCopyInto(out)
	return out
}
